apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD
             valueFrom:
	secretKeyRef:
		name: mysql-parameters
		key: password
        ports:
	- containerPort: 80
	  name: mysql
        volumeMounts:
	- name: mysql-pvc
	   mountPath: /var/lib/mysql   
      volumes:
	- name: mysql-pvc
	   persistentVolumeClaim:
		claimName: mysql-pvc
		