apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
	name: prov-role-binder
subjects:
	- kind: ServiceAccount
	   name: efs-RB
	   namespace: default
roleRef:
	kind: ClusterRole
	name: cluster-admin
	apiGroup: rbac.authorization.k8s.io